// ============================================================================
// FIRST BREACH — ART PACK KIT (Hudson const layout + wall skin w/ buttresses)
// ----------------------------------------------------------------------------
// Hand-placed props (big arched gates, pillars, torches, ward, rubble) + a full-height wall
// skin: wall_cracked tiled along every perimeter wall in two stacked courses, with a wall_pillar
// BUTTRESS every ~12 cells so the wall pattern protrudes in a rhythm, + wall_corner at corners.
// Primitive perimeter walls are hidden by the renderer while this kit is active (?fbKit=0 = off).
// Visual-only; collision stays the grid (blockedZones). asset = dungeonKit loadName.
// ============================================================================

import { gridToWorld } from "../sim/pathing.js";

export const FIRST_BREACH_KIT = Object.freeze([
  {"id":"wall-0","asset":"wall_arched","col":65,"row":7,"y":0,"ry":0,"scale":2.2,"cat":"wall"},
  {"id":"light-1","asset":"torch_lit","col":63,"row":8,"y":1.3,"ry":0,"scale":0.5,"cat":"light"},
  {"id":"light-2","asset":"wall_inset_candles","col":65,"row":6,"y":1.3,"ry":0,"scale":1,"cat":"light"},
  {"id":"wall-3","asset":"wall_arched","col":5,"row":6,"y":0,"ry":0,"scale":1.8,"cat":"wall"},
  {"id":"wall-4","asset":"wall_arched","col":22,"row":6,"y":0,"ry":0,"scale":1.8,"cat":"wall"},
  {"id":"wall-5","asset":"wall_arched","col":66,"row":30,"y":0,"ry":90,"scale":1.8,"cat":"wall"},
  {"id":"wall-6","asset":"wall_arched","col":66,"row":52,"y":0,"ry":90,"scale":1.8,"cat":"wall"},
  {"id":"pillar-7","asset":"pillar","col":27,"row":7,"y":1.3,"ry":0,"scale":0.65,"cat":"pillar"},
  {"id":"pillar-8","asset":"pillar","col":33,"row":7,"y":1.3,"ry":0,"scale":0.65,"cat":"pillar"},
  {"id":"pillar-9","asset":"pillar","col":57,"row":7,"y":1.3,"ry":0,"scale":0.65,"cat":"pillar"},
  {"id":"pillar-10","asset":"pillar","col":3,"row":35,"y":2.6,"ry":0,"scale":0.65,"cat":"pillar"},
  {"id":"pillar-11","asset":"pillar","col":5,"row":23,"y":2.6,"ry":0,"scale":0.65,"cat":"pillar"},
  {"id":"pillar-12","asset":"column","col":10,"row":8,"y":2.6,"ry":0,"scale":0.6,"cat":"pillar"},
  {"id":"pillar-13","asset":"column","col":64,"row":48,"y":2.6,"ry":0,"scale":0.6,"cat":"pillar"},
  {"id":"ward-14","asset":"pillar_decorated","col":6,"row":49,"y":3,"ry":0,"scale":0.6,"cat":"ward"},
  {"id":"ward-15","asset":"pillar_decorated","col":12,"row":53,"y":3,"ry":0,"scale":0.6,"cat":"ward"},
  {"id":"ward-16","asset":"resource/Gems_Pile_Large","col":11,"row":51,"y":3,"ry":20,"scale":0.5,"cat":"ward"},
  {"id":"rubble-17","asset":"rubble_large","col":26,"row":8,"y":1.3,"ry":18,"scale":0.5,"cat":"rubble"},
  {"id":"rubble-18","asset":"rubble_large","col":37,"row":38,"y":1.3,"ry":8,"scale":0.5,"cat":"rubble"},
  {"id":"rubble-19","asset":"rubble_large","col":64,"row":44,"y":1.3,"ry":30,"scale":0.5,"cat":"rubble"},
  {"id":"rubble-20","asset":"rubble_half","col":11,"row":35,"y":2.6,"ry":24,"scale":0.5,"cat":"rubble"},
  {"id":"rubble-21","asset":"rocks_small","col":63,"row":54,"y":2.6,"ry":342,"scale":0.45,"cat":"rubble"},
  {"id":"light-22","asset":"torch_lit","col":24,"row":8,"y":1.3,"ry":0,"scale":0.5,"cat":"light"},
  {"id":"light-23","asset":"torch_lit","col":64,"row":50,"y":2.6,"ry":0,"scale":0.5,"cat":"light"},
  {"id":"light-24","asset":"torch_lit","col":13,"row":51,"y":3,"ry":0,"scale":0.5,"cat":"light"},
  {"id":"light-25","asset":"wall_inset_candles","col":33,"row":6,"y":1.3,"ry":0,"scale":0.8,"cat":"light"},
  {"id":"wall-26","asset":"wall_cracked","col":2,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-27","asset":"wall_cracked","col":2,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-28","asset":"wall_pillar","col":10,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-29","asset":"wall_pillar","col":10,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-30","asset":"wall_cracked","col":14,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-31","asset":"wall_cracked","col":14,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-32","asset":"wall_cracked","col":18,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-33","asset":"wall_cracked","col":18,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-34","asset":"wall_pillar","col":26,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-35","asset":"wall_pillar","col":26,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-36","asset":"wall_cracked","col":30,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-37","asset":"wall_cracked","col":30,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-38","asset":"wall_cracked","col":34,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-39","asset":"wall_cracked","col":34,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-40","asset":"wall_pillar","col":38,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-41","asset":"wall_pillar","col":38,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-42","asset":"wall_cracked","col":42,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-43","asset":"wall_cracked","col":42,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-44","asset":"wall_cracked","col":46,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-45","asset":"wall_cracked","col":46,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-46","asset":"wall_pillar","col":50,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-47","asset":"wall_pillar","col":50,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-48","asset":"wall_cracked","col":54,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-49","asset":"wall_cracked","col":54,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-50","asset":"wall_cracked","col":58,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-51","asset":"wall_cracked","col":58,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-52","asset":"wall_pillar","col":62,"row":6,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-53","asset":"wall_pillar","col":62,"row":6,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-54","asset":"wall_cracked","col":1,"row":8,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-55","asset":"wall_cracked","col":1,"row":8,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-56","asset":"wall_pillar","col":1,"row":12,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-57","asset":"wall_pillar","col":1,"row":12,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-58","asset":"wall_cracked","col":1,"row":16,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-59","asset":"wall_cracked","col":1,"row":16,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-60","asset":"wall_cracked","col":66,"row":12,"y":0,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-61","asset":"wall_cracked","col":66,"row":12,"y":3.6,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-62","asset":"wall_pillar","col":66,"row":16,"y":0,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-63","asset":"wall_pillar","col":66,"row":16,"y":3.6,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-64","asset":"wall_cracked","col":66,"row":20,"y":0,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-65","asset":"wall_cracked","col":66,"row":20,"y":3.6,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-66","asset":"wall_cracked","col":66,"row":24,"y":0,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-67","asset":"wall_cracked","col":66,"row":24,"y":3.6,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-68","asset":"wall_pillar","col":66,"row":36,"y":0,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-69","asset":"wall_pillar","col":66,"row":36,"y":3.6,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-70","asset":"wall_cracked","col":66,"row":40,"y":0,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-71","asset":"wall_cracked","col":66,"row":40,"y":3.6,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-72","asset":"wall_cracked","col":66,"row":44,"y":0,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-73","asset":"wall_cracked","col":66,"row":44,"y":3.6,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-74","asset":"wall_pillar","col":66,"row":48,"y":0,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-75","asset":"wall_pillar","col":66,"row":48,"y":3.6,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-76","asset":"wall_cracked","col":1,"row":25,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-77","asset":"wall_cracked","col":1,"row":25,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-78","asset":"wall_pillar","col":1,"row":29,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-79","asset":"wall_pillar","col":1,"row":29,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-80","asset":"wall_cracked","col":1,"row":33,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-81","asset":"wall_cracked","col":1,"row":33,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-82","asset":"wall_cracked","col":0,"row":38,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-83","asset":"wall_cracked","col":0,"row":38,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-84","asset":"wall_pillar","col":0,"row":42,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-85","asset":"wall_pillar","col":0,"row":42,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-86","asset":"wall_cracked","col":0,"row":46,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-87","asset":"wall_cracked","col":0,"row":46,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-88","asset":"wall_cracked","col":0,"row":50,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-89","asset":"wall_cracked","col":0,"row":50,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-90","asset":"wall_pillar","col":0,"row":54,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-91","asset":"wall_pillar","col":0,"row":54,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-92","asset":"wall_cracked","col":2,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-93","asset":"wall_cracked","col":2,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-94","asset":"wall_pillar","col":6,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-95","asset":"wall_pillar","col":6,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-96","asset":"wall_cracked","col":10,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-97","asset":"wall_cracked","col":10,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-98","asset":"wall_cracked","col":14,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-99","asset":"wall_cracked","col":14,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-100","asset":"wall_pillar","col":18,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-101","asset":"wall_pillar","col":18,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-102","asset":"wall_cracked","col":22,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-103","asset":"wall_cracked","col":22,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-104","asset":"wall_cracked","col":26,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-105","asset":"wall_cracked","col":26,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-106","asset":"wall_pillar","col":30,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-107","asset":"wall_pillar","col":30,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-108","asset":"wall_cracked","col":34,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-109","asset":"wall_cracked","col":34,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-110","asset":"wall_cracked","col":38,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-111","asset":"wall_cracked","col":38,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-112","asset":"wall_pillar","col":42,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-113","asset":"wall_pillar","col":42,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-114","asset":"wall_cracked","col":46,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-115","asset":"wall_cracked","col":46,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-116","asset":"wall_cracked","col":50,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-117","asset":"wall_cracked","col":50,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-118","asset":"wall_pillar","col":54,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-119","asset":"wall_pillar","col":54,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-120","asset":"wall_cracked","col":58,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-121","asset":"wall_cracked","col":58,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-122","asset":"wall_cracked","col":62,"row":56,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-123","asset":"wall_cracked","col":62,"row":56,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-124","asset":"wall_corner","col":0,"row":6,"y":0,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-125","asset":"wall_corner","col":0,"row":6,"y":3.6,"ry":90,"scale":1,"cat":"wall"},
  {"id":"wall-126","asset":"wall_corner","col":66,"row":6,"y":0,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-127","asset":"wall_corner","col":66,"row":6,"y":3.6,"ry":180,"scale":1,"cat":"wall"},
  {"id":"wall-128","asset":"wall_corner","col":0,"row":56,"y":0,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-129","asset":"wall_corner","col":0,"row":56,"y":3.6,"ry":0,"scale":1,"cat":"wall"},
  {"id":"wall-130","asset":"wall_corner","col":66,"row":56,"y":0,"ry":270,"scale":1,"cat":"wall"},
  {"id":"wall-131","asset":"wall_corner","col":66,"row":56,"y":3.6,"ry":270,"scale":1,"cat":"wall"}
]);

export const FIRST_BREACH_KIT_ASSET_NAMES = Object.freeze([...new Set(FIRST_BREACH_KIT.map((s) => s.asset))]);

export function firstBreachKitSpecs(level) {
  return FIRST_BREACH_KIT.map((s) => {
    const w = gridToWorld(s.col, s.row, level);
    return { ...s, x: w.x, z: w.z };
  });
}
