export const MAP_PIECE_PACKS = Object.freeze(["dungeon", "rpgtools", "resource"]);

const gltf = (pack, name) => ({
  pack,
  name,
  runtimeName: pack === "dungeon" ? name : `${pack}/${name}`,
  url: `models/${pack}/${name}.gltf`,
  publicPath: `public/models/${pack}/${name}.gltf`,
});

const fallback = (primitive = "box", material = "stone", scale = { x: 1, y: 1, z: 1 }) => ({
  primitive,
  material,
  scale,
});

export const MAP_PIECES = Object.freeze({
  "ruined-gate": {
    key: "ruined-gate",
    type: "gate",
    label: "Ruined Gate",
    asset: gltf("dungeon", "wall_gated"),
    fallback: fallback("box", "stone", { x: 3.2, y: 2.2, z: 0.35 }),
    tags: ["spawn", "wall", "stone"],
  },
  "arched-gate": {
    key: "arched-gate",
    type: "gate",
    label: "Arched Gate",
    asset: gltf("dungeon", "wall_archedwindow_gated"),
    fallback: fallback("box", "stone", { x: 3.0, y: 2.4, z: 0.35 }),
    tags: ["spawn", "wall", "stone"],
  },
  "arched-gate-scaffold": {
    key: "arched-gate-scaffold",
    type: "gate",
    label: "Scaffolded Arched Gate",
    asset: gltf("dungeon", "wall_archedwindow_gated_scaffold"),
    fallback: fallback("box", "stone", { x: 3.2, y: 2.45, z: 0.4 }),
    tags: ["spawn", "wall", "stone", "scaffold"],
  },
  "crypt-corner-gate": {
    key: "crypt-corner-gate",
    type: "gate",
    label: "Crypt Corner Gate",
    asset: gltf("dungeon", "wall_corner_gated"),
    fallback: fallback("box", "stone", { x: 2.7, y: 2.25, z: 1.2 }),
    tags: ["spawn", "crypt", "wall", "stone"],
  },
  "green-banner": {
    key: "green-banner",
    type: "prop",
    label: "Green Banner",
    asset: gltf("dungeon", "banner_shield_green"),
    fallback: fallback("box", "plague", { x: 0.28, y: 1.35, z: 0.08 }),
    tags: ["spawn", "readability", "green"],
  },
  "lit-torch": {
    key: "lit-torch",
    type: "prop",
    label: "Lit Torch",
    asset: gltf("dungeon", "torch_lit"),
    fallback: fallback("cylinder", "gold", { x: 0.18, y: 0.9, z: 0.18 }),
    tags: ["spawn", "light", "readability"],
  },
  "low-wall": {
    key: "low-wall",
    type: "wall",
    label: "Low Wall",
    asset: gltf("dungeon", "wall_half"),
    fallback: fallback("box", "stone", { x: 2.4, y: 0.75, z: 0.28 }),
    tags: ["edge", "wall", "stone"],
  },
  "broken-wall": {
    key: "broken-wall",
    type: "wall",
    label: "Broken Wall",
    asset: gltf("dungeon", "wall_broken"),
    fallback: fallback("box", "stone", { x: 2.5, y: 1.7, z: 0.34 }),
    tags: ["background", "wall", "ruin", "stone"],
  },
  "cracked-wall": {
    key: "cracked-wall",
    type: "wall",
    label: "Cracked Wall",
    asset: gltf("dungeon", "wall_cracked"),
    fallback: fallback("box", "stone", { x: 2.5, y: 1.9, z: 0.34 }),
    tags: ["background", "wall", "ruin", "stone"],
  },
  "retaining-wall-half": {
    key: "retaining-wall-half",
    type: "edge",
    label: "Retaining Half Wall",
    asset: gltf("dungeon", "wall_half_endcap"),
    fallback: fallback("box", "stone", { x: 1.8, y: 0.75, z: 0.28 }),
    tags: ["edge", "wall", "platform", "stone"],
  },
  "retaining-wall-sloped": {
    key: "retaining-wall-sloped",
    type: "edge",
    label: "Sloped Retaining Wall",
    asset: gltf("dungeon", "wall_half_endcap_sloped"),
    fallback: fallback("box", "stone", { x: 1.9, y: 0.65, z: 0.28 }),
    tags: ["edge", "wall", "platform", "stone"],
  },
  "lane-edge-barrier": {
    key: "lane-edge-barrier",
    type: "edge",
    label: "Lane Edge Barrier",
    asset: gltf("dungeon", "barrier_half"),
    fallback: fallback("box", "stone", { x: 1.9, y: 0.45, z: 0.22 }),
    tags: ["edge", "lane", "readability"],
  },
  "broken-floor-tile": {
    key: "broken-floor-tile",
    type: "laneFloor",
    label: "Broken Floor Tile",
    asset: gltf("dungeon", "floor_tile_small_broken_A"),
    fallback: fallback("box", "stone", { x: 1.05, y: 0.08, z: 1.05 }),
    tags: ["floor", "lane", "stone"],
  },
  "stone-floor-large": {
    key: "stone-floor-large",
    type: "laneFloor",
    label: "Large Stone Floor",
    asset: gltf("dungeon", "floor_tile_large"),
    fallback: fallback("box", "stone", { x: 1.35, y: 0.08, z: 1.35 }),
    tags: ["floor", "lane", "stone"],
  },
  "lane-floor-rocks": {
    key: "lane-floor-rocks",
    type: "laneFloor",
    label: "Rocky Lane Floor",
    asset: gltf("dungeon", "floor_tile_large_rocks"),
    fallback: fallback("box", "stone", { x: 1.35, y: 0.08, z: 1.35 }),
    tags: ["floor", "lane", "rubble", "stone"],
  },
  "grate-threshold": {
    key: "grate-threshold",
    type: "laneFloor",
    label: "Grate Threshold",
    asset: gltf("dungeon", "floor_tile_big_grate"),
    fallback: fallback("box", "stone", { x: 1.45, y: 0.08, z: 1.45 }),
    tags: ["floor", "spawn", "threshold", "stone"],
  },
  "weed-floor-a": {
    key: "weed-floor-a",
    type: "laneFloor",
    label: "Weedy Stone Floor A",
    asset: gltf("dungeon", "floor_tile_small_weeds_A"),
    fallback: fallback("box", "stone", { x: 1.05, y: 0.08, z: 1.05 }),
    tags: ["floor", "lane", "weeds", "stone"],
  },
  "weed-floor-b": {
    key: "weed-floor-b",
    type: "laneFloor",
    label: "Weedy Stone Floor B",
    asset: gltf("dungeon", "floor_tile_small_weeds_B"),
    fallback: fallback("box", "stone", { x: 1.05, y: 0.08, z: 1.05 }),
    tags: ["floor", "lane", "weeds", "stone"],
  },
  "stone-stair-short": {
    key: "stone-stair-short",
    type: "stair",
    label: "Short Stone Stair",
    asset: gltf("dungeon", "stairs_wide"),
    fallback: fallback("box", "stone", { x: 3.4, y: 0.55, z: 2.0 }),
    tags: ["verticality", "stair", "stone"],
  },
  "ruined-stone-stair-short": {
    key: "ruined-stone-stair-short",
    type: "stair",
    label: "Ruined Stone Stair Short",
    asset: gltf("dungeon", "stairs"),
    fallback: fallback("box", "stone", { x: 2.2, y: 0.45, z: 1.4 }),
    tags: ["verticality", "stair", "stone"],
  },
  "ruined-stone-stair-wide": {
    key: "ruined-stone-stair-wide",
    type: "stair",
    label: "Ruined Stone Stair Wide",
    asset: gltf("dungeon", "stairs_wide"),
    fallback: fallback("box", "stone", { x: 3.4, y: 0.55, z: 2.0 }),
    tags: ["verticality", "stair", "stone"],
  },
  "ruined-stone-stair-long": {
    key: "ruined-stone-stair-long",
    type: "stair",
    label: "Ruined Stone Stair Long",
    asset: gltf("dungeon", "stairs_long"),
    fallback: fallback("box", "stone", { x: 2.6, y: 0.65, z: 3.8 }),
    tags: ["verticality", "stair", "stone"],
  },
  "modular-stair-center": {
    key: "modular-stair-center",
    type: "stair",
    label: "Modular Stair Center",
    asset: gltf("dungeon", "stairs_modular_center"),
    fallback: fallback("box", "stone", { x: 1.2, y: 0.4, z: 1.6 }),
    tags: ["verticality", "stair", "stone", "modular"],
  },
  "modular-stair-left": {
    key: "modular-stair-left",
    type: "stair",
    label: "Modular Stair Left",
    asset: gltf("dungeon", "stairs_modular_left"),
    fallback: fallback("box", "stone", { x: 1.2, y: 0.4, z: 1.6 }),
    tags: ["verticality", "stair", "stone", "modular"],
  },
  "modular-stair-right": {
    key: "modular-stair-right",
    type: "stair",
    label: "Modular Stair Right",
    asset: gltf("dungeon", "stairs_modular_right"),
    fallback: fallback("box", "stone", { x: 1.2, y: 0.4, z: 1.6 }),
    tags: ["verticality", "stair", "stone", "modular"],
  },
  "stone-landing": {
    key: "stone-landing",
    type: "landing",
    label: "Stone Landing",
    asset: gltf("dungeon", "floor_foundation_front_and_sides"),
    fallback: fallback("box", "stone", { x: 3.0, y: 0.28, z: 3.0 }),
    tags: ["verticality", "platform", "landing", "stone"],
  },
  "raised-platform-edge": {
    key: "raised-platform-edge",
    type: "platform",
    label: "Raised Platform Edge",
    asset: gltf("dungeon", "floor_foundation_front"),
    fallback: fallback("box", "stone", { x: 3.0, y: 0.28, z: 1.2 }),
    tags: ["verticality", "platform", "edge", "stone"],
  },
  "raised-foundation": {
    key: "raised-foundation",
    type: "platform",
    label: "Raised Foundation",
    asset: gltf("dungeon", "floor_foundation_allsides"),
    fallback: fallback("box", "stone", { x: 3.0, y: 0.35, z: 3.0 }),
    tags: ["verticality", "platform", "stone"],
  },
  "ward-gem-small": {
    key: "ward-gem-small",
    type: "shrine",
    label: "Small Ward Gem",
    asset: gltf("resource", "Gem_Small"),
    fallback: fallback("sphere", "plague", { x: 0.35, y: 0.35, z: 0.35 }),
    tags: ["ward", "crystal", "green"],
  },
  "ward-gem-medium": {
    key: "ward-gem-medium",
    type: "shrine",
    label: "Medium Ward Gem",
    asset: gltf("resource", "Gem_Medium"),
    fallback: fallback("sphere", "plague", { x: 0.55, y: 0.55, z: 0.55 }),
    tags: ["ward", "crystal", "green"],
  },
  "ritual-candle": {
    key: "ritual-candle",
    type: "shrine",
    label: "Ritual Candle",
    asset: gltf("dungeon", "candle_lit"),
    fallback: fallback("cylinder", "gold", { x: 0.14, y: 0.42, z: 0.14 }),
    tags: ["ward", "light"],
  },
  "candle-triple": {
    key: "candle-triple",
    type: "shrine",
    label: "Triple Candle",
    asset: gltf("dungeon", "candle_triple"),
    fallback: fallback("cylinder", "gold", { x: 0.25, y: 0.35, z: 0.25 }),
    tags: ["ward", "light", "candle"],
  },
  "candle-thin-lit": {
    key: "candle-thin-lit",
    type: "shrine",
    label: "Thin Lit Candle",
    asset: gltf("dungeon", "candle_thin_lit"),
    fallback: fallback("cylinder", "gold", { x: 0.1, y: 0.46, z: 0.1 }),
    tags: ["ward", "light", "candle"],
  },
  "gems-pile-small": {
    key: "gems-pile-small",
    type: "shrine",
    label: "Small Gem Pile",
    asset: gltf("resource", "Gems_Pile_Small"),
    fallback: fallback("sphere", "plague", { x: 0.45, y: 0.22, z: 0.45 }),
    tags: ["ward", "crystal", "green"],
  },
  "stone-bricks-small": {
    key: "stone-bricks-small",
    type: "prop",
    label: "Small Stone Brick Stack",
    asset: gltf("resource", "Stone_Bricks_Stack_Small"),
    fallback: fallback("box", "stone", { x: 0.55, y: 0.32, z: 0.4 }),
    tags: ["background", "stone", "rubble"],
  },
  "broken-sword-shield": {
    key: "broken-sword-shield",
    type: "prop",
    label: "Broken Sword and Shield",
    asset: gltf("dungeon", "sword_shield_broken"),
    fallback: fallback("box", "gold", { x: 0.7, y: 0.1, z: 0.45 }),
    tags: ["ward", "background", "battlefield"],
  },
  "decorated-pillar": {
    key: "decorated-pillar",
    type: "prop",
    label: "Decorated Pillar",
    asset: gltf("dungeon", "pillar_decorated"),
    fallback: fallback("cylinder", "stone", { x: 0.42, y: 1.4, z: 0.42 }),
    tags: ["background", "ruin", "stone"],
  },
  "wall-inset-candles": {
    key: "wall-inset-candles",
    type: "wall",
    label: "Wall Inset with Candles",
    asset: gltf("dungeon", "wall_inset_candles"),
    fallback: fallback("box", "stone", { x: 2.1, y: 1.7, z: 0.32 }),
    tags: ["background", "wall", "light", "stone"],
  },
  "decorated-rocks": {
    key: "decorated-rocks",
    type: "prop",
    label: "Decorated Rocks",
    asset: gltf("dungeon", "rocks_decorated"),
    fallback: fallback("box", "stone", { x: 0.8, y: 0.35, z: 0.65 }),
    tags: ["background", "rubble", "stone"],
  },
  "crates-stacked": {
    key: "crates-stacked",
    type: "prop",
    label: "Stacked Crates",
    asset: gltf("dungeon", "crates_stacked"),
    fallback: fallback("box", "stone", { x: 0.75, y: 0.65, z: 0.75 }),
    tags: ["background", "courtyard", "supply"],
  },
  "decorated-barrel": {
    key: "decorated-barrel",
    type: "prop",
    label: "Decorated Barrel",
    asset: gltf("dungeon", "barrel_large_decorated"),
    fallback: fallback("cylinder", "stone", { x: 0.45, y: 0.7, z: 0.45 }),
    tags: ["background", "courtyard", "supply"],
  },
  "rubble-small": {
    key: "rubble-small",
    type: "prop",
    label: "Small Rubble",
    asset: gltf("dungeon", "rubble_half"),
    fallback: fallback("box", "stone", { x: 0.8, y: 0.28, z: 0.55 }),
    tags: ["background", "rubble", "stone"],
  },
  "field-map": {
    key: "field-map",
    type: "prop",
    label: "Field Map",
    asset: gltf("rpgtools", "map"),
    fallback: fallback("box", "gold", { x: 0.8, y: 0.04, z: 0.55 }),
    tags: ["background", "planning"],
  },
  "primitive-readability-ring": {
    key: "primitive-readability-ring",
    type: "readabilityMarker",
    label: "Readability Ring",
    fallback: fallback("cylinder", "plague", { x: 1, y: 0.03, z: 1 }),
    tags: ["readability", "fallback"],
  },
});

export function mapPiecePack(piece) {
  return piece?.asset?.pack || null;
}

export function mapPieceRuntimeName(piece) {
  return piece?.asset?.runtimeName || null;
}
