// All defences, two per order. Data only. The mission shows a player only their
// class's towers (see kits.js).
//
// Phase A defense foundation:
// - defenseType describes DD1-style behavior: blockade, turret, trap, or aura.
// - fireRate is the legacy combat field currently used by World.
// - attackRate mirrors fireRate for the new defense data model and future code.
// Stage A1 does not change behavior yet; it only makes categories explicit.

export const TOWERS = {
  // --- Warden - The Wall (blockers / frontline) ---
  barricade: {
    id: "barricade",
    name: "Warden Barricade",
    order: "Warden",
    cost: 40,
    defenseType: "blockade",
    physical: true,
    blocksEnemies: true,
    targetableByEnemies: true,
    hp: 380,
    maxHp: 380,
    blockRadius: 0.68,
    contactRadius: 0.68,
    contactDamage: 0,
    contactTickRate: 0,
    range: 1.4,
    damage: 0,
    fireRate: 1.2,
    attackRate: 1.2,
    projSpeed: Infinity,
    splash: 0,
    color: "plague",
    roleText: "Blocks enemies | High health wall",
    blurb: "A heavy warded wall that holds lanes and buys time for repairs.",
  },

  // Spike-gate is a blockade variant: a physical gate for lane control that
  // trades raw HP for teeth when enemies press against it.
  spikegate: {
    id: "spikegate",
    name: "Spike-gate",
    order: "Warden",
    cost: 55,
    defenseType: "blockade",
    physical: true,
    blocksEnemies: true,
    targetableByEnemies: true,
    hp: 240,
    maxHp: 240,
    blockRadius: 0.6,
    contactRadius: 0.72,
    contactDamage: 4,
    contactTickRate: 1.25,
    range: 1.9,
    damage: 20,
    fireRate: 1.6,
    attackRate: 1.6,
    projSpeed: Infinity,
    splash: 0,
    color: "ash",
    blurb: "Hard melee bite at the corners.",
  },

  // --- Hunter - The Long-eyes (traps / ranged) ---
  trapstake: {
    id: "trapstake",
    name: "Trap-stake",
    order: "Hunter",
    cost: 45,
    defenseType: "trap",
    physical: false,
    blocksEnemies: false,
    targetableByEnemies: false,
    hp: 0,
    maxHp: 0,
    blockRadius: 0,
    range: 2.2,
    damage: 14,
    fireRate: 1.5,
    attackRate: 1.5,
    projSpeed: Infinity,
    splash: 0,
    charges: 6,
    resetTime: 1.4,
    triggerRadius: 1.1,
    color: "plague",
    blurb: "Ground spikes that gut anything passing.",
  },
  ballista: {
    id: "ballista",
    name: "Ballista",
    order: "Hunter",
    cost: 75,
    defenseType: "turret",
    physical: true,
    blocksEnemies: false,
    targetableByEnemies: true,
    hp: 180,
    maxHp: 180,
    blockRadius: 0.4,
    range: 5.5,
    damage: 44,
    fireRate: 0.7,
    attackRate: 0.7,
    projSpeed: 14,
    splash: 0,
    color: "bone",
    blurb: "Long reach, heavy single-target bolts.",
  },

  // --- Stormcaller - The Stormcallers (projectile magic) ---
  spire: {
    id: "spire",
    name: "Elemental Spire",
    order: "Stormcaller",
    cost: 80,
    defenseType: "turret",
    physical: true,
    blocksEnemies: false,
    targetableByEnemies: true,
    hp: 150,
    maxHp: 150,
    blockRadius: 0.35,
    range: 3.2,
    damage: 16,
    fireRate: 1.1,
    attackRate: 1.1,
    projSpeed: 9,
    splash: 1.1,
    color: "plague",
    blurb: "Splash for clustered dead.",
  },
  tempest: {
    id: "tempest",
    name: "Tempest Spire",
    order: "Stormcaller",
    cost: 115,
    defenseType: "turret",
    physical: true,
    blocksEnemies: false,
    targetableByEnemies: true,
    hp: 140,
    maxHp: 140,
    blockRadius: 0.35,
    range: 4.0,
    damage: 24,
    fireRate: 0.8,
    attackRate: 0.8,
    projSpeed: 10,
    splash: 1.7,
    color: "plague",
    blurb: "Wider, heavier storm bursts.",
  },

  // --- Plague Doctor - The Mercy (auras / support) ---
  censer: {
    id: "censer",
    name: "Poison Censer",
    order: "Plague Doctor",
    cost: 70,
    defenseType: "aura",
    physical: false,
    blocksEnemies: false,
    targetableByEnemies: false,
    hp: 0,
    maxHp: 0,
    blockRadius: 0,
    range: 2.8,
    damage: 10,
    fireRate: 2.2,
    attackRate: 2.2,
    projSpeed: Infinity,
    splash: 1.2,
    duration: 45,
    tickRate: 2.2,
    effect: { type: "damage", element: "rot" },
    color: "rot",
    blurb: "Rapid choking miasma, hits groups.",
  },
  brazier: {
    id: "brazier",
    name: "Ember Brazier",
    order: "Plague Doctor",
    cost: 90,
    defenseType: "aura",
    physical: false,
    blocksEnemies: false,
    targetableByEnemies: false,
    hp: 0,
    maxHp: 0,
    blockRadius: 0,
    range: 3.0,
    damage: 18,
    fireRate: 1.0,
    attackRate: 1.0,
    projSpeed: 8,
    splash: 1.0,
    duration: 35,
    tickRate: 1.0,
    effect: { type: "damage", element: "blood" },
    color: "blood",
    blurb: "Searing embers that rot the breach.",
  },
};
