// Catalog every placeable model (dungeon/resource/rpgtools packs) -> src/view/fbAssetManifest.js
// Categories are inferred from name prefixes. Run: node scripts/genAssetManifest.mjs
import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const PACKS = [["dungeon", ""], ["resource", "resource/"], ["rpgtools", "rpgtools/"]];
const CAT_RULES = [
  [/^wall/, "walls"], [/^floor/, "floors"], [/^stairs/, "stairs"], [/^pillar|^column|^post$/, "pillars"],
  [/^banner/, "banners"], [/^barrier|^scaffold/, "wood"], [/^torch|^candle|lantern/, "lights"],
  [/^barrel|^crate|^box|^keg|^trunk|^bucket|Containers_|Pallet_/, "containers"],
  [/^chest|^coin|^key|Gems?_|Gold_|Silver_|Copper_|Money_|treasure/i, "treasure"],
  [/^table|^chair|^stool|^bench|^bed|^bookcase|^shelf|^shelves|^bar_|^bartop/, "furniture"],
  [/^rocks|^rubble|^bone/, "rubble"], [/^banner/, "banners"],
  [/^plate|^bottle|^book$|^book_|^food|Food_/, "props"],
];
const cat = (n) => { for (const [re, c] of CAT_RULES) if (re.test(n)) return c; return "props"; };

const entries = [];
for (const [dir, prefix] of PACKS) {
  const files = readdirSync(join(root, "public/models", dir)).filter((f) => f.endsWith(".gltf"));
  for (const f of files) {
    const base = f.replace(/\.gltf$/, "");
    entries.push({ name: prefix + base, cat: cat(base), pack: dir });
  }
}
entries.sort((a, b) => a.cat.localeCompare(b.cat) || a.name.localeCompare(b.name));
const cats = [...new Set(entries.map((e) => e.cat))].sort();
const out = `// AUTO-GENERATED by scripts/genAssetManifest.mjs — every placeable model + category.
export const FB_ASSET_MANIFEST = Object.freeze(${JSON.stringify(entries)});
export const FB_ASSET_CATEGORIES = Object.freeze(${JSON.stringify(cats)});
`;
writeFileSync(join(root, "src/view/fbAssetManifest.js"), out);
console.log(`manifest: ${entries.length} models, ${cats.length} categories:`, cats.join(", "));
