import { LEVEL } from "../config/level.js";
import { ACTIVE_MAP_THEME_ID } from "../config/mapThemes.js";
import { buildMapPlacements } from "./mapBuilder.js";

const SPAWN_DRESSING = Object.freeze({
  "north-gate": { rotation: 0, gate: "ruined-gate", torchOffset: 1.9, bannerOffset: 2.35, dz: -0.45 },
  "northwest-stairs": { rotation: 0, gate: "arched-gate-scaffold", torchOffset: 1.65, bannerOffset: 2.15, dz: -0.45 },
  "northeast-market": { rotation: 0, gate: "arched-gate-scaffold", torchOffset: 1.65, bannerOffset: 2.15, dz: -0.45 },
  "southwest-crypt": { rotation: 90, gate: "crypt-corner-gate", torchOffset: 1.75, bannerOffset: 2.2, dx: -0.45 },
  "southeast-garden": { rotation: -90, gate: "crypt-corner-gate", torchOffset: 1.75, bannerOffset: 2.2, dx: 0.45 },
});

const LANE_FLOOR_KEYS = ["broken-floor-tile", "stone-floor-large", "lane-floor-rocks", "weed-floor-a", "weed-floor-b"];
const MACRO_FLOOR_KEYS = ["stone-floor-large", "lane-floor-rocks", "broken-floor-tile", "weed-floor-a"];

function floorMaterialTokenForBand(band) {
  if (band === "shrine") return "shrinePlatformStone";
  if (band === "high") return "landingHighStone";
  if (band === "mid") return "courtyardMidStone";
  return "courtyardLowStone";
}

function laneHintMaterialToken(tele, level) {
  const coreRow = level.core?.row ?? 10;
  if (tele.row <= coreRow + 8) return "shrinePlatformStone";
  if (tele.row <= 36) return "landingHighStone";
  if (tele.row <= 46) return "courtyardMidStone";
  return "courtyardLowStone";
}

export function firstBreachElevationPlan(level = LEVEL) {
  const core = level.core || { col: 36, row: 10 };
  return {
    id: "first-breach-elevation-intent-v1",
    mapId: "first-breach",
    visualOnly: true,
    zones: [
      {
        id: "front-courtyard-low",
        band: "low",
        bounds: { col: 24, row: 47, w: 25, h: 10 },
        role: "lower approach court and central spawn threshold",
        floorMaterial: "broken courtyard stone",
        edgeTreatment: "low ruin shoulders",
        allowGameplayOverlap: true,
        tags: ["approach", "central-stair", "spawn"],
      },
      {
        id: "central-stair-mid",
        band: "mid",
        bounds: { col: 31, row: 39, w: 11, h: 10 },
        role: "visual transition up the central route",
        floorMaterial: "stepped stone bands",
        edgeTreatment: "retaining wall cheeks",
        allowGameplayOverlap: true,
        tags: ["connector", "central-stair"],
      },
      {
        id: "main-landing-high",
        band: "high",
        bounds: { col: 29, row: 32, w: 15, h: 8 },
        role: "main choke landing before the Ward approach",
        floorMaterial: "stone landing and macro slabs",
        edgeTreatment: "main choke ward stones",
        allowGameplayOverlap: true,
        tags: ["choke", "landing"],
      },
      {
        id: "ward-shrine",
        band: "shrine",
        bounds: { col: core.col - 6, row: core.row - 4, w: 13, h: 11 },
        role: "raised Ward Crystal focal platform",
        floorMaterial: "Ward-green ritual stone and pedestal",
        edgeTreatment: "platform wings, pedestal edge, rear framing",
        allowGameplayOverlap: true,
        tags: ["ward", "objective", "focal-point"],
      },
      {
        id: "left-crypt-low",
        band: "low",
        bounds: { col: 0, row: 24, w: 18, h: 12 },
        role: "left side crypt breach approach",
        floorMaterial: "crypt threshold stone",
        edgeTreatment: "crypt frame and rubble edge",
        allowGameplayOverlap: true,
        tags: ["crypt", "side-breach"],
      },
      {
        id: "right-crypt-low",
        band: "low",
        bounds: { col: level.cols - 18, row: 24, w: 18, h: 12 },
        role: "right side crypt breach approach",
        floorMaterial: "crypt threshold stone",
        edgeTreatment: "crypt frame and rubble edge",
        allowGameplayOverlap: true,
        tags: ["crypt", "side-breach"],
      },
      {
        id: "rear-cathedral-background",
        band: "backgroundHigh",
        bounds: { col: 16, row: 4, w: 41, h: 8 },
        role: "rear ruin silhouette framing the Ward shrine",
        floorMaterial: "shadowed ruined stone",
        edgeTreatment: "broken walls and candle inset silhouettes",
        allowGameplayOverlap: true,
        tags: ["background", "edge", "cathedral"],
      },
    ],
    connectors: [
      {
        id: "central-stair-connector",
        type: "stair",
        fromZone: "front-courtyard-low",
        toZone: "main-landing-high",
        laneId: "north-gate",
        entryCell: { col: 36, row: 52 },
        exitCell: { col: 36, row: 35 },
        width: 3,
        stepCount: 9,
        landingCells: {
          bottom: { col: 36, row: 52 },
          mid: { col: 36, row: 43 },
          top: { col: 36, row: 35 },
        },
        edgeTreatment: "left and right retaining cheek walls",
        visualOnly: true,
        tags: ["central-stair", "main-lane"],
      },
      {
        id: "left-front-terrace",
        type: "terrace",
        fromZone: "front-courtyard-low",
        toZone: "main-landing-high",
        laneId: "northwest-stairs",
        entryCell: { col: 16, row: 52 },
        exitCell: { col: 32, row: 34 },
        width: 2,
        landingCells: {
          bottom: { col: 16, row: 49 },
          top: { col: 32, row: 34 },
        },
        edgeTreatment: "lane-side retaining edge and choke wall",
        visualOnly: true,
        tags: ["front-breach", "left"],
      },
      {
        id: "right-front-terrace",
        type: "terrace",
        fromZone: "front-courtyard-low",
        toZone: "main-landing-high",
        laneId: "northeast-market",
        entryCell: { col: 56, row: 52 },
        exitCell: { col: 40, row: 34 },
        width: 2,
        landingCells: {
          bottom: { col: 56, row: 49 },
          top: { col: 40, row: 34 },
        },
        edgeTreatment: "lane-side retaining edge and market choke wall",
        visualOnly: true,
        tags: ["front-breach", "right"],
      },
      {
        id: "left-crypt-terrace",
        type: "terrace",
        fromZone: "left-crypt-low",
        toZone: "main-landing-high",
        laneId: "southwest-crypt",
        entryCell: { col: 2, row: 30 },
        exitCell: { col: 26, row: 28 },
        width: 2,
        landingCells: {
          bottom: { col: 6, row: 30 },
          top: { col: 26, row: 28 },
        },
        edgeTreatment: "crypt gate frame and rubble depth",
        visualOnly: true,
        tags: ["crypt", "left"],
      },
      {
        id: "right-crypt-terrace",
        type: "terrace",
        fromZone: "right-crypt-low",
        toZone: "main-landing-high",
        laneId: "southeast-garden",
        entryCell: { col: 70, row: 30 },
        exitCell: { col: 46, row: 28 },
        width: 2,
        landingCells: {
          bottom: { col: 66, row: 30 },
          top: { col: 46, row: 28 },
        },
        edgeTreatment: "crypt gate frame and garden ruin edge",
        visualOnly: true,
        tags: ["crypt", "right"],
      },
      {
        id: "ward-approach-terrace",
        type: "terrace",
        fromZone: "main-landing-high",
        toZone: "ward-shrine",
        laneId: "north-gate",
        entryCell: { col: 36, row: 22 },
        exitCell: { col: core.col, row: core.row + 3 },
        width: 3,
        landingCells: {
          bottom: { col: 36, row: 22 },
          top: { col: core.col, row: core.row + 3 },
        },
        edgeTreatment: "Ward apron, pedestal edge, and shrine wings",
        visualOnly: true,
        tags: ["ward", "fallback-choke"],
      },
    ],
  };
}

function spawnGateCluster(lane) {
  const spec = SPAWN_DRESSING[lane.id] || SPAWN_DRESSING["north-gate"];
  const sideAxis = Math.abs(spec.rotation) === 90 ? "z" : "x";
  const forwardAxis = Math.abs(spec.rotation) === 90 ? "x" : "z";
  const gateOffset = {
    [forwardAxis]: spec[forwardAxis === "x" ? "dx" : "dz"] || 0,
  };
  const side = (value) => ({ [sideAxis]: value, [forwardAxis]: spec[forwardAxis === "x" ? "dx" : "dz"] || 0 });

  return {
    id: `${lane.id}-spawn-gate`,
    type: "cluster",
    laneId: lane.id,
    cell: lane.spawn,
    readabilityRole: "spawn-gate",
    allowOverlapGameplay: true,
    tags: ["spawn", "readability", "mapbuilder"],
    children: [
      {
        id: "gate",
        type: "gate",
        assetKey: spec.gate,
        offset: gateOffset,
        rotation: spec.rotation,
        scale: lane.id === "north-gate" ? 1.12 : 0.96,
      },
      {
        id: "left-torch",
        assetKey: "lit-torch",
        offset: side(-spec.torchOffset),
        rotation: spec.rotation,
        scale: 0.72,
      },
      {
        id: "right-torch",
        assetKey: "lit-torch",
        offset: side(spec.torchOffset),
        rotation: spec.rotation,
        scale: 0.72,
      },
      {
        id: "left-banner",
        assetKey: "green-banner",
        offset: side(-spec.bannerOffset),
        rotation: spec.rotation + 8,
        scale: 0.76,
      },
      {
        id: "right-banner",
        assetKey: "green-banner",
        offset: side(spec.bannerOffset),
        rotation: spec.rotation - 8,
        scale: 0.76,
      },
    ],
  };
}

function laneFloorHints(level) {
  return (level.laneTelegraphs || [])
    .filter((tele) => (tele.index || 0) % 4 === 0)
    .map((tele, index) => ({
      id: `${tele.laneId}-lane-hint-${index}`,
      type: "laneFloor",
      assetKey: LANE_FLOOR_KEYS[index % LANE_FLOOR_KEYS.length],
      laneId: tele.laneId,
      cell: { col: tele.col, row: tele.row },
      readabilityRole: "lane-art",
      allowOverlapGameplay: true,
      visualY: 0.055,
      scale: 0.68 + ((tele.col + tele.row) % 3) * 0.06,
      rotation: ((tele.col * 19 + tele.row * 13) % 80) - 40,
      materialToken: laneHintMaterialToken(tele, level),
      tags: ["lane", "path-aligned", "mapbuilder"],
    }));
}

function laneChokeMarkers(level) {
  const pieces = [];
  for (const lane of level.lanes || []) {
    if (lane.choke) {
      pieces.push({
        id: `${lane.id}-main-choke-ring`,
        type: "readabilityMarker",
        assetKey: "primitive-readability-ring",
        laneId: lane.id,
        cell: lane.choke,
        readabilityRole: "main-choke",
        allowOverlapGameplay: true,
        materialToken: "wardChokeGlyph",
        scale: { x: 1.46, y: 1, z: 1.46 },
        tags: ["choke", "main", "mapbuilder"],
      });
    }
    if (lane.fallbackChoke) {
      pieces.push({
        id: `${lane.id}-fallback-choke-ring`,
        type: "readabilityMarker",
        assetKey: "primitive-readability-ring",
        laneId: lane.id,
        cell: lane.fallbackChoke,
        readabilityRole: "fallback-choke",
        allowOverlapGameplay: true,
        materialToken: "wardRuneSoft",
        scale: { x: 1.08, y: 1, z: 1.08 },
        tags: ["choke", "fallback", "mapbuilder"],
      });
    }
    (lane.buildShoulders || []).slice(0, 2).forEach((shoulder, index) => {
      pieces.push({
        id: `${lane.id}-shoulder-edge-${index}`,
        type: "edge",
        assetKey: "lane-edge-barrier",
        laneId: lane.id,
        cell: shoulder,
        readabilityRole: "build-shoulder",
        rotation: lane.spawn.col < level.core.col ? 12 : -12,
        materialToken: "shadowEdgeRuin",
        scale: 0.5,
        tags: ["build-space", "lane-edge", "mapbuilder"],
      });
    });
  }
  return pieces;
}

function chokeWardStones(level) {
  return (level.lanes || []).filter((lane) => lane.choke).flatMap((lane, index) => {
    const sideSign = lane.choke.col < level.core.col ? -1 : lane.choke.col > level.core.col ? 1 : (index % 2 ? -1 : 1);
    const forward = lane.choke.row > level.core.row ? 0.45 : -0.45;
    const fallbackSide = -sideSign;
    const fallbackForward = lane.fallbackChoke?.row > level.core.row ? 0.35 : -0.35;
    const mainStone = {
      id: `${lane.id}-choke-ward-stone`,
      type: "shrine",
      assetKey: index % 2 === 0 ? "stone-bricks-small" : "candle-thin-lit",
      laneId: lane.id,
      cell: lane.choke,
      offset: { x: sideSign * 0.92, z: forward },
      readabilityRole: "in-world-choke-marker",
      allowOverlapGameplay: true,
      materialToken: index % 2 === 0 ? "shadowEdgeRuin" : "torchWarm",
      scale: index % 2 === 0 ? 0.34 : 0.4,
      rotation: lane.spawn.col < level.core.col ? -18 : 18,
      tags: ["choke", "ward-rune", "mapbuilder"],
    };
    const fallbackStone = lane.fallbackChoke ? {
      id: `${lane.id}-fallback-ward-stone`,
      type: "shrine",
      assetKey: index % 2 === 0 ? "ward-gem-small" : "stone-bricks-small",
      laneId: lane.id,
      cell: lane.fallbackChoke,
      offset: { x: fallbackSide * 0.74, z: fallbackForward },
      readabilityRole: "in-world-choke-marker",
      allowOverlapGameplay: true,
      materialToken: index % 2 === 0 ? "wardRuneSoft" : "shadowEdgeRuin",
      scale: index % 2 === 0 ? 0.28 : 0.3,
      rotation: lane.spawn.col < level.core.col ? 20 : -20,
      tags: ["choke", "fallback", "ward-rune", "mapbuilder"],
    } : null;
    return fallbackStone ? [mainStone, fallbackStone] : [mainStone];
  });
}

function laneWardMarkers(level) {
  const laneCounts = new Map();
  return (level.laneTelegraphs || [])
    .filter((tele) => (tele.index || 0) % 5 === 2)
    .map((tele) => {
      const count = laneCounts.get(tele.laneId) || 0;
      laneCounts.set(tele.laneId, count + 1);
      const lateral = tele.dir === "east" || tele.dir === "west"
        ? { x: 0, z: count % 2 ? -0.46 : 0.46 }
        : { x: count % 2 ? -0.46 : 0.46, z: 0 };
      return {
        id: `${tele.laneId}-ward-floor-marker-${count}`,
        type: "shrine",
        assetKey: count % 3 === 0 ? "ward-gem-small" : "stone-bricks-small",
        laneId: tele.laneId,
        cell: { col: tele.col, row: tele.row },
        offset: lateral,
        readabilityRole: "in-world-lane-marker",
        allowOverlapGameplay: true,
        visualY: 0.075,
        materialToken: count % 3 === 0 ? "wardCrackGlow" : laneHintMaterialToken(tele, level),
        scale: count % 3 === 0 ? 0.22 : 0.26,
        rotation: ((tele.col * 17 + tele.row * 23) % 90) - 45,
        tags: ["lane", "ward-rune", "path-aligned", "mapbuilder"],
      };
    });
}

function macroFloorBreakup() {
  const patches = [
    { id: "front-courtyard-west-field", col: 29, row: 51, scale: 1.28, rot: -19, zone: "front-courtyard-low", band: "low", y: 0.014, assetKey: "stone-floor-large" },
    { id: "front-courtyard-east-field", col: 43, row: 51, scale: 1.28, rot: 17, zone: "front-courtyard-low", band: "low", y: 0.014, assetKey: "stone-floor-large" },
    { id: "central-lower-left", col: 33, row: 50, scale: 0.95, rot: -8, zone: "front-courtyard-low", band: "low", y: 0.018 },
    { id: "central-lower-mid", col: 36, row: 50, scale: 1.04, rot: 3, zone: "front-courtyard-low", band: "low", y: 0.018 },
    { id: "central-lower-right", col: 39, row: 50, scale: 0.95, rot: 9, zone: "front-courtyard-low", band: "low", y: 0.018 },
    { id: "mid-courtyard-west-slab", col: 30, row: 43, scale: 1.2, rot: 31, zone: "central-stair-mid", band: "mid", y: 0.078, assetKey: "lane-floor-rocks" },
    { id: "mid-courtyard-east-slab", col: 42, row: 43, scale: 1.2, rot: -29, zone: "central-stair-mid", band: "mid", y: 0.078, assetKey: "lane-floor-rocks" },
    { id: "mid-courtyard-left-broad-chip", col: 27, row: 40, scale: 1.06, rot: -34, zone: "central-stair-mid", band: "mid", y: 0.076, assetKey: "stone-floor-large" },
    { id: "mid-courtyard-right-broad-chip", col: 45, row: 40, scale: 1.06, rot: 34, zone: "central-stair-mid", band: "mid", y: 0.076, assetKey: "stone-floor-large" },
    { id: "central-mid-left", col: 33, row: 44, scale: 1.02, rot: 12, zone: "central-stair-mid", band: "mid", y: 0.085 },
    { id: "central-mid-right", col: 39, row: 44, scale: 1.02, rot: -12, zone: "central-stair-mid", band: "mid", y: 0.085 },
    { id: "high-landing-center-slab", col: 36, row: 35, scale: 1.16, rot: 45, zone: "main-landing-high", band: "high", y: 0.155, assetKey: "stone-floor-large" },
    { id: "central-landing-left", col: 32, row: 35, scale: 0.96, rot: -18, zone: "main-landing-high", band: "high", y: 0.16 },
    { id: "central-landing-right", col: 40, row: 35, scale: 0.96, rot: 18, zone: "main-landing-high", band: "high", y: 0.16 },
    { id: "fallback-left-apron", col: 32, row: 22, scale: 0.92, rot: 26, zone: "main-landing-high", band: "high", y: 0.15 },
    { id: "fallback-right-apron", col: 40, row: 22, scale: 0.92, rot: -26, zone: "main-landing-high", band: "high", y: 0.15 },
    { id: "fallback-center-worn-slab", col: 36, row: 22, scale: 0.86, rot: 45, zone: "main-landing-high", band: "high", y: 0.152, assetKey: "broken-floor-tile" },
    { id: "ward-front-left-apron", col: 32, row: 16, scale: 1.0, rot: -10, zone: "ward-shrine", band: "shrine", y: 0.19 },
    { id: "ward-front-right-apron", col: 40, row: 16, scale: 1.0, rot: 10, zone: "ward-shrine", band: "shrine", y: 0.19 },
    { id: "ward-approach-center-slab", col: 36, row: 16, scale: 0.84, rot: 0, zone: "ward-shrine", band: "shrine", y: 0.195, assetKey: "lane-floor-rocks" },
    { id: "ward-rear-slab", col: 36, row: 13, scale: 1.05, rot: 45, zone: "ward-shrine", band: "shrine", y: 0.2 },
  ];

  return patches.map((patch, index) => ({
    id: `macro-floor-${patch.id}`,
    type: "laneFloor",
    assetKey: patch.assetKey || MACRO_FLOOR_KEYS[index % MACRO_FLOOR_KEYS.length],
    cell: { col: patch.col, row: patch.row },
    readabilityRole: "macro-floor-breakup",
    allowOverlapGameplay: true,
    visualY: patch.y,
    elevationZone: patch.zone,
    elevationBand: patch.band,
    scale: patch.scale,
    rotation: patch.rot,
    materialToken: floorMaterialTokenForBand(patch.band),
    tags: ["floor", "macro-shape", "elevation-zone", "mapbuilder"],
  }));
}

function centralStairArchitecture() {
  const shared = {
    laneId: "north-gate",
    allowOverlapGameplay: true,
    tags: ["verticality", "central-stair", "elevation-connector", "mapbuilder"],
  };
  const stairRows = [
    { band: "lower", row: 50, scale: 0.8, visualY: 0.035, elevationZone: "front-courtyard-low", elevationBand: "low" },
    { band: "lower-mid", row: 47, scale: 0.79, visualY: 0.062, elevationZone: "central-stair-mid", elevationBand: "mid" },
    { band: "middle", row: 44, scale: 0.77, visualY: 0.09, elevationZone: "central-stair-mid", elevationBand: "mid" },
    { band: "upper-mid", row: 41, scale: 0.75, visualY: 0.12, elevationZone: "central-stair-mid", elevationBand: "mid" },
    { band: "upper", row: 38, scale: 0.73, visualY: 0.148, elevationZone: "main-landing-high", elevationBand: "high" },
  ];
  const stairPieces = stairRows.flatMap((run) => [
    {
      id: `central-stair-${run.band}-left`,
      type: "stair",
      assetKey: "modular-stair-left",
      cell: { col: 34, row: run.row },
      readabilityRole: "visual-stair",
      visualY: run.visualY,
      elevationZone: run.elevationZone,
      elevationBand: run.elevationBand,
      materialToken: "ruinedStoneStep",
      scale: run.scale,
      ...shared,
    },
    {
      id: run.band === "lower" ? "central-stair-lower-run" : `central-stair-${run.band}-center`,
      type: "stair",
      assetKey: "modular-stair-center",
      cell: { col: 36, row: run.row },
      readabilityRole: "visual-stair",
      visualY: run.visualY + 0.006,
      elevationZone: run.elevationZone,
      elevationBand: run.elevationBand,
      materialToken: "ruinedStoneStep",
      scale: run.scale,
      ...shared,
    },
    {
      id: `central-stair-${run.band}-right`,
      type: "stair",
      assetKey: "modular-stair-right",
      cell: { col: 38, row: run.row },
      readabilityRole: "visual-stair",
      visualY: run.visualY,
      elevationZone: run.elevationZone,
      elevationBand: run.elevationBand,
      materialToken: "ruinedStoneStep",
      scale: run.scale,
      ...shared,
    },
  ]);
  const cheekRows = [
    { row: 50, scale: 0.5, visualY: 0.034, zone: "front-courtyard-low", band: "low" },
    { row: 47, scale: 0.52, visualY: 0.062, zone: "central-stair-mid", band: "mid" },
    { row: 44, scale: 0.54, visualY: 0.09, zone: "central-stair-mid", band: "mid" },
    { row: 41, scale: 0.56, visualY: 0.12, zone: "central-stair-mid", band: "mid" },
    { row: 38, scale: 0.58, visualY: 0.148, zone: "main-landing-high", band: "high" },
    { row: 35, scale: 0.6, visualY: 0.17, zone: "main-landing-high", band: "high" },
  ];
  const retainingEdges = cheekRows.flatMap((edge) => [
    {
      id: `central-stair-left-cheek-${edge.row}`,
      type: "edge",
      assetKey: edge.row <= 41 ? "retaining-wall-sloped" : "retaining-wall-half",
      cell: { col: 32, row: edge.row },
      readabilityRole: "stair-retaining-edge",
      rotation: 90,
      scale: edge.scale,
      visualY: edge.visualY,
      elevationZone: edge.zone,
      elevationBand: edge.band,
      materialToken: edge.band === "high" ? "landingHighStone" : edge.band === "mid" ? "courtyardMidStone" : "floorRubbleDark",
      ...shared,
    },
    {
      id: `central-stair-right-cheek-${edge.row}`,
      type: "edge",
      assetKey: edge.row <= 41 ? "retaining-wall-sloped" : "retaining-wall-half",
      cell: { col: 40, row: edge.row },
      readabilityRole: "stair-retaining-edge",
      rotation: 90,
      scale: edge.scale,
      visualY: edge.visualY,
      elevationZone: edge.zone,
      elevationBand: edge.band,
      materialToken: edge.band === "high" ? "landingHighStone" : edge.band === "mid" ? "courtyardMidStone" : "floorRubbleDark",
      ...shared,
    },
  ]);

  return [
    {
      id: "central-spawn-threshold-grate",
      type: "laneFloor",
      assetKey: "grate-threshold",
      cell: { col: 36, row: 53 },
      readabilityRole: "spawn-threshold",
      elevationZone: "front-courtyard-low",
      elevationBand: "low",
      materialToken: "spawnThresholdBlood",
      scale: 0.82,
      ...shared,
    },
    {
      id: "central-stair-bottom-landing",
      type: "landing",
      assetKey: "stone-landing",
      cell: { col: 36, row: 52 },
      readabilityRole: "stair-landing",
      visualY: 0.02,
      elevationZone: "front-courtyard-low",
      elevationBand: "low",
      materialToken: "courtyardLowStone",
      scale: 0.78,
      rotation: 180,
      ...shared,
      tags: [...shared.tags, "bottom-landing"],
    },
    ...stairPieces,
    {
      id: "central-stair-mid-landing",
      type: "landing",
      assetKey: "stone-landing",
      cell: { col: 36, row: 43 },
      readabilityRole: "stair-landing",
      visualY: 0.096,
      elevationZone: "central-stair-mid",
      elevationBand: "mid",
      materialToken: "courtyardMidStone",
      scale: 0.72,
      rotation: 180,
      ...shared,
      tags: [...shared.tags, "mid-landing"],
    },
    ...retainingEdges,
    {
      id: "central-main-landing",
      type: "landing",
      assetKey: "stone-landing",
      cell: { col: 36, row: 35 },
      readabilityRole: "stair-landing",
      visualY: 0.175,
      elevationZone: "main-landing-high",
      elevationBand: "high",
      materialToken: "landingHighStone",
      scale: 0.82,
      rotation: 180,
      ...shared,
      tags: [...shared.tags, "top-landing"],
    },
    {
      id: "central-main-landing-left-edge",
      type: "platform",
      assetKey: "raised-platform-edge",
      cell: { col: 32, row: 35 },
      readabilityRole: "stair-top-landing-edge",
      visualY: 0.16,
      elevationZone: "main-landing-high",
      elevationBand: "high",
      materialToken: "floorRubbleDark",
      scale: 0.62,
      rotation: 18,
      ...shared,
    },
    {
      id: "central-main-landing-right-edge",
      type: "platform",
      assetKey: "raised-platform-edge",
      cell: { col: 40, row: 35 },
      readabilityRole: "stair-top-landing-edge",
      visualY: 0.16,
      elevationZone: "main-landing-high",
      elevationBand: "high",
      materialToken: "floorRubbleDark",
      scale: 0.62,
      rotation: -18,
      ...shared,
    },
  ];
}

function frontBreachArchitecture() {
  const lanes = [
    {
      laneId: "northwest-stairs",
      side: "left",
      cells: [
        { id: "lower-edge", cell: { col: 20, row: 43 }, assetKey: "retaining-wall-half", rotation: 0 },
        { id: "turn-edge", cell: { col: 26, row: 39 }, assetKey: "retaining-wall-sloped", rotation: 90 },
        { id: "choke-wall", cell: { col: 29, row: 33 }, assetKey: "low-wall", rotation: 0 },
        { id: "threshold", cell: { col: 16, row: 49 }, assetKey: "grate-threshold", rotation: 0, type: "laneFloor" },
        { id: "market-rubble", cell: { col: 23, row: 41 }, assetKey: "decorated-rocks", rotation: 18, type: "prop" },
      ],
    },
    {
      laneId: "northeast-market",
      side: "right",
      cells: [
        { id: "lower-edge", cell: { col: 52, row: 43 }, assetKey: "retaining-wall-half", rotation: 0 },
        { id: "turn-edge", cell: { col: 46, row: 39 }, assetKey: "retaining-wall-sloped", rotation: 90 },
        { id: "choke-wall", cell: { col: 43, row: 33 }, assetKey: "low-wall", rotation: 0 },
        { id: "threshold", cell: { col: 56, row: 49 }, assetKey: "grate-threshold", rotation: 0, type: "laneFloor" },
        { id: "market-crates", cell: { col: 51, row: 41 }, assetKey: "crates-stacked", rotation: -18, type: "prop" },
      ],
    },
  ];
  return lanes.flatMap((lane) => lane.cells.map((piece) => ({
    id: `${lane.laneId}-${piece.id}`,
    type: piece.type || "edge",
    assetKey: piece.assetKey,
    laneId: lane.laneId,
    cell: piece.cell,
    readabilityRole: `front-breach-${lane.side}`,
    allowOverlapGameplay: true,
    scale: piece.scale || 0.62,
    rotation: piece.rotation || 0,
    tags: ["front-breach", "lane-edge", "mapbuilder"],
  })));
}

function cryptBreachArchitecture() {
  const crypts = [
    { laneId: "southwest-crypt", side: "left", gateCell: { col: 4, row: 30 }, wallCell: { col: 5, row: 27 }, pillarCell: { col: 6, row: 33 }, rubbleCell: { col: 10, row: 29 }, rotation: 90 },
    { laneId: "southeast-garden", side: "right", gateCell: { col: 68, row: 30 }, wallCell: { col: 67, row: 27 }, pillarCell: { col: 66, row: 33 }, rubbleCell: { col: 62, row: 29 }, rotation: -90 },
  ];
  return crypts.flatMap((crypt) => [
    {
      id: `${crypt.laneId}-inner-crypt-gate`,
      type: "gate",
      assetKey: "wall-inset-candles",
      laneId: crypt.laneId,
      cell: crypt.gateCell,
      readabilityRole: "crypt-breach-frame",
      allowOverlapGameplay: true,
      scale: 0.64,
      rotation: crypt.rotation,
      tags: ["crypt", "spawn", "mapbuilder"],
    },
    {
      id: `${crypt.laneId}-broken-crypt-wall`,
      type: "wall",
      assetKey: "broken-wall",
      laneId: crypt.laneId,
      cell: crypt.wallCell,
      readabilityRole: "crypt-breach-frame",
      allowOverlapGameplay: true,
      scale: 0.56,
      rotation: crypt.rotation,
      tags: ["crypt", "ruin", "mapbuilder"],
    },
    {
      id: `${crypt.laneId}-crypt-pillar`,
      type: "prop",
      assetKey: "decorated-pillar",
      laneId: crypt.laneId,
      cell: crypt.pillarCell,
      readabilityRole: "crypt-breach-frame",
      allowOverlapGameplay: true,
      scale: 0.58,
      rotation: 0,
      tags: ["crypt", "ruin", "mapbuilder"],
    },
    {
      id: `${crypt.laneId}-crypt-floor-grate`,
      type: "laneFloor",
      assetKey: "grate-threshold",
      laneId: crypt.laneId,
      cell: { col: crypt.side === "left" ? 6 : 66, row: 30 },
      readabilityRole: "crypt-threshold",
      allowOverlapGameplay: true,
      scale: 0.72,
      rotation: crypt.rotation,
      tags: ["crypt", "threshold", "mapbuilder"],
    },
    {
      id: `${crypt.laneId}-crypt-rubble-depth`,
      type: "prop",
      assetKey: "decorated-rocks",
      laneId: crypt.laneId,
      cell: crypt.rubbleCell,
      readabilityRole: "crypt-breach-depth",
      allowOverlapGameplay: true,
      scale: 0.54,
      rotation: crypt.side === "left" ? 24 : -24,
      tags: ["crypt", "rubble", "mapbuilder"],
    },
  ]);
}

function wardShrinePieces(level) {
  const core = level.core || { col: 36, row: 10 };
  return [
    {
      id: "ward-shrine-raised-foundation",
      type: "platform",
      assetKey: "raised-foundation",
      cell: core,
      readabilityRole: "ward-shrine",
      allowOverlapGameplay: true,
      visualY: 0.02,
      elevationZone: "ward-shrine",
      elevationBand: "shrine",
      materialToken: "shrinePlatformStone",
      scale: 1.18,
      rotation: 45,
      tags: ["ward", "platform", "elevation-zone", "mapbuilder"],
    },
    {
      id: "ward-shrine-core-pedestal",
      type: "platform",
      assetKey: "raised-foundation",
      cell: core,
      readabilityRole: "ward-shrine",
      allowOverlapGameplay: true,
      visualY: 0.09,
      elevationZone: "ward-shrine",
      elevationBand: "shrine",
      materialToken: "landingHighStone",
      scale: 0.58,
      rotation: 45,
      tags: ["ward", "platform", "pedestal", "elevation-zone", "mapbuilder"],
    },
    {
      id: "ward-shrine-green-ring",
      type: "readabilityMarker",
      assetKey: "primitive-readability-ring",
      cell: core,
      readabilityRole: "ward-shrine",
      allowOverlapGameplay: true,
      materialToken: "wardHaloGreen",
      visualY: 0.045,
      scale: { x: 3.65, y: 1, z: 3.65 },
      tags: ["ward", "ring", "mapbuilder"],
    },
    {
      id: "ward-shrine-left-gem",
      type: "shrine",
      assetKey: "ward-gem-small",
      cell: core,
      offset: { x: -2.0, z: 1.7 },
      readabilityRole: "ward-shrine",
      allowOverlapGameplay: true,
      elevationZone: "ward-shrine",
      elevationBand: "shrine",
      visualY: 0.11,
      scale: 0.72,
      rotation: -20,
      tags: ["ward", "gem", "mapbuilder"],
    },
    {
      id: "ward-shrine-right-gem",
      type: "shrine",
      assetKey: "ward-gem-medium",
      cell: core,
      offset: { x: 2.0, z: 1.7 },
      readabilityRole: "ward-shrine",
      allowOverlapGameplay: true,
      elevationZone: "ward-shrine",
      elevationBand: "shrine",
      visualY: 0.11,
      scale: 0.62,
      rotation: 20,
      tags: ["ward", "gem", "mapbuilder"],
    },
    {
      id: "ward-shrine-north-candle",
      type: "shrine",
      assetKey: "ritual-candle",
      cell: core,
      offset: { z: -2.55 },
      readabilityRole: "ward-shrine",
      allowOverlapGameplay: true,
      elevationZone: "ward-shrine",
      elevationBand: "shrine",
      visualY: 0.1,
      scale: 0.72,
      tags: ["ward", "candle", "mapbuilder"],
    },
    {
      id: "ward-shrine-south-candle",
      type: "shrine",
      assetKey: "ritual-candle",
      cell: core,
      offset: { z: 2.55 },
      readabilityRole: "ward-shrine",
      allowOverlapGameplay: true,
      elevationZone: "ward-shrine",
      elevationBand: "shrine",
      visualY: 0.1,
      scale: 0.72,
      tags: ["ward", "candle", "mapbuilder"],
    },
  ];
}

function wardShrineDepthPieces(level) {
  const core = level.core || { col: 36, row: 10 };
  const shared = {
    readabilityRole: "ward-shrine",
    allowOverlapGameplay: true,
    elevationZone: "ward-shrine",
    elevationBand: "shrine",
    tags: ["ward", "shrine-depth", "elevation-zone", "mapbuilder"],
  };
  const approachShared = {
    laneId: "north-gate",
    readabilityRole: "ward-approach-terrace",
    allowOverlapGameplay: true,
    elevationZone: "main-landing-high",
    elevationBand: "high",
    tags: ["ward", "ward-approach", "elevation-connector", "mapbuilder"],
  };
  return [
    {
      id: "ward-approach-lower-landing",
      type: "landing",
      assetKey: "stone-landing",
      cell: { col: core.col, row: core.row + 12 },
      visualY: 0.15,
      materialToken: "landingHighStone",
      scale: 0.72,
      rotation: 180,
      ...approachShared,
    },
    {
      id: "ward-approach-upper-landing",
      type: "landing",
      assetKey: "stone-landing",
      cell: { col: core.col, row: core.row + 7 },
      visualY: 0.19,
      materialToken: "shrinePlatformStone",
      scale: 0.66,
      rotation: 180,
      ...approachShared,
      elevationZone: "ward-shrine",
      elevationBand: "shrine",
    },
    {
      id: "ward-approach-left-retaining-edge",
      type: "edge",
      assetKey: "retaining-wall-half",
      cell: { col: core.col - 4, row: core.row + 9 },
      visualY: 0.17,
      materialToken: "floorRubbleDark",
      scale: 0.58,
      rotation: 90,
      ...approachShared,
    },
    {
      id: "ward-approach-right-retaining-edge",
      type: "edge",
      assetKey: "retaining-wall-half",
      cell: { col: core.col + 4, row: core.row + 9 },
      visualY: 0.17,
      materialToken: "floorRubbleDark",
      scale: 0.58,
      rotation: 90,
      ...approachShared,
    },
    {
      id: "ward-shrine-front-landing",
      type: "landing",
      assetKey: "stone-landing",
      cell: { col: core.col, row: core.row + 3 },
      visualY: 0.2,
      materialToken: "shrinePlatformStone",
      scale: 0.78,
      rotation: 180,
      ...shared,
    },
    {
      id: "ward-shrine-rear-platform-edge",
      type: "platform",
      assetKey: "raised-platform-edge",
      cell: { col: core.col, row: core.row - 3 },
      visualY: 0.18,
      materialToken: "floorRubbleDark",
      scale: 0.82,
      ...shared,
    },
    {
      id: "ward-shrine-front-pedestal-edge",
      type: "platform",
      assetKey: "raised-platform-edge",
      cell: { col: core.col, row: core.row + 5 },
      visualY: 0.16,
      materialToken: "floorRubbleDark",
      scale: 0.9,
      rotation: 180,
      ...shared,
    },
    {
      id: "ward-shrine-left-platform-wing",
      type: "platform",
      assetKey: "raised-foundation",
      cell: { col: core.col - 4, row: core.row + 2 },
      visualY: 0.14,
      materialToken: "shrinePlatformStone",
      scale: 0.62,
      rotation: 20,
      ...shared,
    },
    {
      id: "ward-shrine-right-platform-wing",
      type: "platform",
      assetKey: "raised-foundation",
      cell: { col: core.col + 4, row: core.row + 2 },
      visualY: 0.14,
      materialToken: "shrinePlatformStone",
      scale: 0.62,
      rotation: -20,
      ...shared,
    },
    {
      id: "ward-shrine-left-retaining-edge",
      type: "edge",
      assetKey: "retaining-wall-half",
      cell: { col: core.col - 4, row: core.row + 1 },
      scale: 0.62,
      rotation: 90,
      visualY: 0.12,
      materialToken: "floorRubbleDark",
      ...shared,
    },
    {
      id: "ward-shrine-right-retaining-edge",
      type: "edge",
      assetKey: "retaining-wall-half",
      cell: { col: core.col + 4, row: core.row + 1 },
      scale: 0.62,
      rotation: 90,
      visualY: 0.12,
      materialToken: "floorRubbleDark",
      ...shared,
    },
    {
      id: "ward-shrine-gem-pile",
      type: "shrine",
      assetKey: "gems-pile-small",
      cell: core,
      offset: { x: 0, z: 3.15 },
      visualY: 0.12,
      scale: 0.48,
      rotation: 30,
      ...shared,
    },
    {
      id: "ward-shrine-brick-stack",
      type: "prop",
      assetKey: "stone-bricks-small",
      cell: core,
      offset: { x: -3.15, z: -1.75 },
      visualY: 0.1,
      scale: 0.54,
      rotation: -28,
      ...shared,
    },
    {
      id: "ward-shrine-broken-arms",
      type: "prop",
      assetKey: "broken-sword-shield",
      cell: core,
      offset: { x: 3.1, z: -1.55 },
      visualY: 0.1,
      scale: 0.48,
      rotation: 110,
      ...shared,
    },
    {
      id: "ward-shrine-left-candle-cluster",
      type: "shrine",
      assetKey: "candle-triple",
      cell: core,
      offset: { x: -1.65, z: 3.1 },
      visualY: 0.1,
      scale: 0.48,
      rotation: -18,
      ...shared,
    },
    {
      id: "ward-shrine-right-candle-cluster",
      type: "shrine",
      assetKey: "candle-triple",
      cell: core,
      offset: { x: 1.65, z: 3.1 },
      visualY: 0.1,
      scale: 0.48,
      rotation: 18,
      ...shared,
    },
  ];
}

function backgroundRuinSilhouettes() {
  return [
    {
      id: "rear-left-platform-edge",
      type: "platform",
      assetKey: "raised-foundation",
      cell: { col: 29, row: 13 },
      readabilityRole: "ward-platform-edge",
      allowOverlapGameplay: true,
      visualY: -0.035,
      scale: 0.78,
      rotation: 18,
      tags: ["verticality", "platform", "mapbuilder"],
    },
    {
      id: "rear-right-platform-edge",
      type: "platform",
      assetKey: "raised-foundation",
      cell: { col: 43, row: 13 },
      readabilityRole: "ward-platform-edge",
      allowOverlapGameplay: true,
      visualY: -0.035,
      scale: 0.78,
      rotation: -18,
      tags: ["verticality", "platform", "mapbuilder"],
    },
    {
      id: "rear-left-broken-wall-depth",
      type: "wall",
      assetKey: "broken-wall",
      cell: { col: 24, row: 6 },
      readabilityRole: "background-depth",
      allowOverlapGameplay: true,
      scale: 0.72,
      rotation: 12,
      tags: ["background", "ruin", "mapbuilder"],
    },
    {
      id: "rear-right-cracked-wall-depth",
      type: "wall",
      assetKey: "cracked-wall",
      cell: { col: 48, row: 6 },
      readabilityRole: "background-depth",
      allowOverlapGameplay: true,
      scale: 0.72,
      rotation: -12,
      tags: ["background", "ruin", "mapbuilder"],
    },
    {
      id: "rear-left-candle-inset-depth",
      type: "wall",
      assetKey: "wall-inset-candles",
      cell: { col: 28, row: 7 },
      readabilityRole: "background-depth",
      allowOverlapGameplay: true,
      scale: 0.52,
      tags: ["background", "ruin", "mapbuilder"],
    },
    {
      id: "rear-right-candle-inset-depth",
      type: "wall",
      assetKey: "wall-inset-candles",
      cell: { col: 44, row: 7 },
      readabilityRole: "background-depth",
      allowOverlapGameplay: true,
      scale: 0.52,
      tags: ["background", "ruin", "mapbuilder"],
    },
    {
      id: "rear-cathedral-left-shoulder",
      type: "wall",
      assetKey: "broken-wall",
      cell: { col: 17, row: 9 },
      readabilityRole: "background-boundary",
      allowOverlapGameplay: true,
      scale: 0.62,
      rotation: 18,
      tags: ["background", "edge", "mapbuilder"],
    },
    {
      id: "rear-cathedral-right-shoulder",
      type: "wall",
      assetKey: "cracked-wall",
      cell: { col: 55, row: 9 },
      readabilityRole: "background-boundary",
      allowOverlapGameplay: true,
      scale: 0.62,
      rotation: -18,
      tags: ["background", "edge", "mapbuilder"],
    },
    {
      id: "front-left-ruin-pillar",
      type: "prop",
      assetKey: "decorated-pillar",
      cell: { col: 28, row: 51 },
      readabilityRole: "background-depth",
      scale: 0.58,
      rotation: 8,
      tags: ["background", "ruin", "mapbuilder"],
    },
    {
      id: "front-right-ruin-pillar",
      type: "prop",
      assetKey: "decorated-pillar",
      cell: { col: 44, row: 51 },
      readabilityRole: "background-depth",
      scale: 0.58,
      rotation: -8,
      tags: ["background", "ruin", "mapbuilder"],
    },
    {
      id: "west-low-boundary-wall",
      type: "wall",
      assetKey: "low-wall",
      cell: { col: 9, row: 39 },
      readabilityRole: "background-boundary",
      materialToken: "shadowEdgeRuin",
      scale: 0.58,
      rotation: 90,
      tags: ["background", "edge", "mapbuilder"],
    },
    {
      id: "west-shadow-ruin-shoulder",
      type: "wall",
      assetKey: "cracked-wall",
      cell: { col: 6, row: 44 },
      readabilityRole: "background-boundary",
      allowOverlapGameplay: true,
      materialToken: "shadowEdgeRuin",
      scale: 0.46,
      rotation: 96,
      tags: ["background", "edge", "shadow", "mapbuilder"],
    },
    {
      id: "west-crypt-frame-wall",
      type: "wall",
      assetKey: "broken-wall",
      cell: { col: 5, row: 23 },
      readabilityRole: "background-boundary",
      allowOverlapGameplay: true,
      materialToken: "shadowEdgeRuin",
      scale: 0.5,
      rotation: 90,
      tags: ["background", "edge", "mapbuilder"],
    },
    {
      id: "east-low-boundary-wall",
      type: "wall",
      assetKey: "low-wall",
      cell: { col: 64, row: 39 },
      readabilityRole: "background-boundary",
      materialToken: "shadowEdgeRuin",
      scale: 0.58,
      rotation: 90,
      tags: ["background", "edge", "mapbuilder"],
    },
    {
      id: "east-shadow-ruin-shoulder",
      type: "wall",
      assetKey: "broken-wall",
      cell: { col: 67, row: 44 },
      readabilityRole: "background-boundary",
      allowOverlapGameplay: true,
      materialToken: "shadowEdgeRuin",
      scale: 0.46,
      rotation: -96,
      tags: ["background", "edge", "shadow", "mapbuilder"],
    },
    {
      id: "east-crypt-frame-wall",
      type: "wall",
      assetKey: "cracked-wall",
      cell: { col: 68, row: 23 },
      readabilityRole: "background-boundary",
      allowOverlapGameplay: true,
      materialToken: "shadowEdgeRuin",
      scale: 0.5,
      rotation: -90,
      tags: ["background", "edge", "mapbuilder"],
    },
    {
      id: "front-left-courtyard-shoulder",
      type: "wall",
      assetKey: "low-wall",
      cell: { col: 24, row: 55 },
      readabilityRole: "background-boundary",
      allowOverlapGameplay: true,
      scale: 0.55,
      rotation: 0,
      tags: ["background", "edge", "mapbuilder"],
    },
    {
      id: "front-right-courtyard-shoulder",
      type: "wall",
      assetKey: "low-wall",
      cell: { col: 48, row: 55 },
      readabilityRole: "background-boundary",
      allowOverlapGameplay: true,
      scale: 0.55,
      rotation: 0,
      tags: ["background", "edge", "mapbuilder"],
    },
    {
      id: "field-planning-map",
      type: "prop",
      assetKey: "field-map",
      cell: { col: 30, row: 48 },
      offset: { x: -0.25, z: -0.55 },
      readabilityRole: "background-story",
      scale: 0.44,
      rotation: -10,
      tags: ["background", "planning", "mapbuilder"],
    },
    {
      id: "crypt-rubble-left",
      type: "prop",
      assetKey: "rubble-small",
      cell: { col: 10, row: 32 },
      readabilityRole: "background-rubble",
      scale: 0.52,
      rotation: 24,
      tags: ["background", "rubble", "mapbuilder"],
    },
    {
      id: "crypt-rubble-right",
      type: "prop",
      assetKey: "rubble-small",
      cell: { col: 63, row: 32 },
      readabilityRole: "background-rubble",
      scale: 0.52,
      rotation: -24,
      tags: ["background", "rubble", "mapbuilder"],
    },
    {
      id: "front-left-shadow-slab",
      type: "laneFloor",
      assetKey: "lane-floor-rocks",
      cell: { col: 19, row: 50 },
      readabilityRole: "background-floor-breakup",
      allowOverlapGameplay: true,
      materialToken: "floorRubbleDark",
      scale: 0.78,
      rotation: -32,
      tags: ["background", "floor", "edge", "mapbuilder"],
    },
    {
      id: "front-right-shadow-slab",
      type: "laneFloor",
      assetKey: "lane-floor-rocks",
      cell: { col: 54, row: 50 },
      readabilityRole: "background-floor-breakup",
      allowOverlapGameplay: true,
      materialToken: "floorRubbleDark",
      scale: 0.78,
      rotation: 32,
      tags: ["background", "floor", "edge", "mapbuilder"],
    },
  ];
}

export function firstBreachMapPlan(level = LEVEL) {
  return {
    id: "first-breach-mapbuilder-macro-shape-v1",
    mapId: "first-breach",
    theme: ACTIVE_MAP_THEME_ID,
    elevationPlan: firstBreachElevationPlan(level),
    intent: "Visual-only macro environment shape pass for compact First Breach readability.",
    pieces: [
      ...(level.lanes || []).map(spawnGateCluster),
      ...laneFloorHints(level),
      ...laneWardMarkers(level),
      ...macroFloorBreakup(level),
      ...laneChokeMarkers(level),
      ...chokeWardStones(level),
      ...centralStairArchitecture(level),
      ...frontBreachArchitecture(level),
      ...cryptBreachArchitecture(level),
      ...wardShrinePieces(level),
      ...wardShrineDepthPieces(level),
      ...backgroundRuinSilhouettes(level),
    ],
  };
}

export const FIRST_BREACH_MAP_PLAN = firstBreachMapPlan(LEVEL);

export function buildFirstBreachMapBuilder(level = LEVEL) {
  return buildMapPlacements(firstBreachMapPlan(level), { level });
}

export function firstBreachMapBuilderAssetNames(level = LEVEL) {
  return buildFirstBreachMapBuilder(level).assetNames;
}
